def greet():
    print('-' * 30)
    print("| Hello!;) I'm glad to see u",                              '|')
    print("| Let's play the logic game!",                              '|')
    print('-' * 37)
    print('|         !Description!             |')
    print('-' * 37)
    print("| AI made the number from 10 to 999 |")
    print("| And U should try to guess this    |")
    print("| Of course, AI will help u!        |")
    print('-' * 59)
    print("| For example, u'ld write a number and if U don't guess   |")
    print("| But your answer've an integer in the number             |")
    print("| The AI write:                                           |")
    print("| 'Your answer have 1 or 2 int in my number'              |")
    print('|              U have 31 attempts!                        |')
    print('-' * 59)
    print('| I hope U can understand me:)                            |')
    print('-' * 59)
